coverage:
  status:
    patch:
      default:
        target: 100%
        threshold: 0%
    project:
      default:
        informational: true

ignore:
  - "tests/**/*"
  - "scripts/**/*"
  - "docs/**/*"
  - "custom_components/habragerone/manifest.json"

comment:
  layout: "reach, diff, flags, files"
  require_changes: true
