name: Draft a release note
on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: read

jobs:
  draft_release:
    name: Release Drafter
    runs-on: ubuntu-latest
    steps:
      - name: Run release-drafter
        uses: release-drafter/release-drafter@3832cfb52f98ab0f0e5b62aecf94909e334d4da6 # v7.5.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}